### PR TITLE
Adds Fn::ForEach support

### PR DESCRIPTION
**Pull request by billyjbryant**
### Description

On July 26, 2023, AWS released support for a [looping function in CloudFormation templates](https://aws.amazon.com/about-aws/whats-new/2023/07/accelerate-cloudformation-authoring-experience-looping-function/) through [`Fn::ForEach`](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/intrinsic-function-reference-foreach.html). 

This PR adds support for using this function to CloudFriend.

### CODE REVIEW

**Review by YannickMeeus — APPROVED** [review]
This was on my list after seeing that announcement! Thanks for adding this 🙏🏼 

Let's not forget to update our internal documentation afterwards, I can share details on how to do this once this has been merged and published to NPM.

**Comment by bilindhajer** [comment]
Lets merge this after this [patch](https://github.com/mapbox/cloudfriend/pull/141) gets released tomm morning. What do you think? @YannickMeeus

**Comment by YannickMeeus** [comment]
@bilindhajer Sorry, lost track of this. I'll merge this, publish it and then update our platform docs.

**Comment by YannickMeeus** [comment]
This has been published as part of cloudfriend@v7.1.0.

Thanks for the contribution @billyjbryant 🙏🏼

**Pull request merged**
