### PR TITLE
cf.shortcuts

### PR DESCRIPTION
**Pull request by rclark**
I write a lot of Lambda functions. Every time I do, I write pretty much the same LogGroup, Role, and Function resource, just with a few different pointers to code in the Lambda function, or a few different statements in the policy document. Same goes for scheduled lambda functions, where I do all that again + add a boilerplate `AWS::Events::Rule` and `AWS::Lambda::Permission`.

The idea here is to write some JS classes to act as "shortcuts" for some of that repetition. I am:

- excited by the possibility of not having to write that same old stuff over and over again forever
- scared of opening the door to the sorts of opinionated decisions that always go into these kinds of definitions
- curious if I should be looking into other solutions (terraform, etc) instead of going this route

I am also curious to hear from @mapbox/platform to see what anyone else thinks about the idea.

---

This PR would:

- be a major version bump
- require users to jump to node 8+ (I believe its time to get aggressive about this)
- replace bespoke eslintrc with https://github.com/mapbox/eslint-config-mapbox
- introduce the `cf.shortcuts` module, with a class for a vanilla Lambda function and a scheduled one
- probably follow up with a kinesis-fed Lambda and an SQS-fed Lambda

Due to the eslint-isms, there are a ton of changes in the PR, but if you're looking it over, pay attention to [shortcuts/lambda.js](https://github.com/mapbox/cloudfriend/pull/32/files#diff-68c9a8541f997a41ccaf0b2d95343ca8) and [readme.md](https://github.com/mapbox/cloudfriend/pull/32/files#diff-0730bb7c2e8f9ea2438b52e419dd86c9).

### CODE REVIEW

**Comment by rclark** [comment]
Note: these Lambda shortcuts should include alarms on error metrics too (I always forget that part)

**Comment by freenerd** [comment]
To me the spirit of `cloudfriend` is to make working with CloudFormation templates easier to providing easier access to low-level CloudFormation concepts, as well as provide helpers like `userData` and `build` and `merge`. It's an easy-to-understand mission statement.

The shortcuts then break that spirit, especially as OP says:

> scared of opening the door to the sorts of opinionated decisions that always go into these kinds of definitions

I share this fear, especially since we will constantly have to balance how opinionated and customizable each shortcut is.

Still, I think shortcuts are useful, saving development time and providing automatically following best practices (e.g. creating alarms). To me, they'd best live in their own module (which in turn can include cloudfriend again). The likely use-case then would be that a user would include `cloudfriend` and `cloudfriend-shortcuts` and can use both together seamlessly. I'd expect `cloudfriend-shortcuts` to quickly bump in versions since we'd add a lot of services. `cloudfriend` would stay with it's core mission and not see rapid version bumps. As a current heavy user of `cloufriend` I'd likely not migrate my existing templates to `cloudfriend-shortcuts`, but would use it for new projects.

> require users to jump to node 8+ (I believe its time to get aggressive about this)
> replace bespoke eslintrc with https://github.com/mapbox/eslint-config-mapbox

👍

**Comment by arunasank** [comment]
> To me, they'd best live in their own module (which in turn can include cloudfriend again). The likely use-case then would be that a user would include cloudfriend and cloudfriend-shortcuts and can use both together seamlessly. I'd expect cloudfriend-shortcuts to quickly bump in versions since we'd add a lot of services. cloudfriend would stay with it's core mission and not see rapid version bumps. As a current heavy user of cloufriend I'd likely not migrate my existing templates to cloudfriend-shortcuts, but would use it for new projects.

+1. 👍

**Comment by rclark** [comment]
Given that we at mapbox (and myself in particular) have a rich history of oversplitting repos when maybe we could manage them better in larger lumps, I want to push back a little on making this another repository. Some thoughts:

- cloudfriend has become a de-facto language for writing cloudformation templates at Mapbox. If we want to advocate a practice of shared shortcuts and best-practices, it'd be better to house them here because they will be discoverable and easier to access.

- no one would ever be required to use shortcuts, you could still use cloudfriend for low-level template construction via intrinsic functions and pseudo parameters.

- "I'd expect cloudfriend-shortcuts to quickly bump in versions since we'd add a lot of services". This is definitely true: its likely that the upgrade cadence on the shortcuts will be very different than the cadence on rest of the library. But concretely what problem does that present?

**Comment by rclark** [comment]
I tried out a Lambda shortcut in another stack and while I like the result, I do not like the API

```js
const RebalanceDisabler = new cf.shortcuts.Lambda(
  'RebalanceDisabler',
  {
    ZipFile: cf.sub(redent(`
      const AWS = require('aws-sdk');
      const response = require('cfn-response');
      const AutoScalingGroupName = '\${AutoScalingGroup}';

      module.exports.handler = (event, context, callback) => {
        const asg = new AWS.AutoScaling();

        const params = {
          AutoScalingGroupName,
          ScalingProcesses: ['AZRebalance']
        };

        asg.suspendProcesses(params)
          .promise()
          .then(() => response.send(event, context, response.SUCCESS))
          .catch((err) => {
            console.error(err.stack);
            response.send(event, context, response.FAILED)
          });
      };
    `).trim())
  },
  'index.handler',
  {
    Runtime: 'nodejs6.10'
  },
  {
    Statement: [
      {
        Effect: 'Allow',
        Action: 'autoscaling:SuspendProcesses',
        Resource: '*'
      }
    ],
    ErrorAlarmProperties: {
      AlarmActions: [sparky.topic()]
    }
  }
);
```

The fact that the function accepts 3 required and 2 input arguments, and that several of the arguments are not simple strings/numbers/boolean, makes it really hard to identify what you're passing in, really hard to read. 

Also, if the provided `Code` object contains a `ZipFile` property, the default `Runtime` should be `nodejs6.10`.

**Comment by rclark** [comment]
The most recent commit flattens the API into a single `options` object. So the above example of a Lambda function collapses to this:

```js
const rebalance = `
  const AWS = require('aws-sdk');
  const response = require('cfn-response');
  const AutoScalingGroupName = '\${AutoScalingGroup}';

  module.exports.handler = (event, context, callback) => {
    const asg = new AWS.AutoScaling();

    const params = {
      AutoScalingGroupName,
      ScalingProcesses: ['AZRebalance']
    };

    asg.suspendProcesses(params)
      .promise()
      .then(() => response.send(event, context, response.SUCCESS))
      .catch((err) => {
        console.error(err.stack);
        response.send(event, context, response.FAILED)
      });
  };
`;

const RebalanceDisabler = new cf.shortcuts.Lambda({
  LogicalName: 'RebalanceDisabler',
  Code: { ZipFile: cf.sub(redent(rebalance).trim()) },
  AlarmActions: ['devnull@nowhere.com'],
  Statement: [{
    Effect: 'Allow',
    Action: 'autoscaling:SuspendProcesses',
    Resource: '*'
  }]
});
```

**Pull request merged**
