### PR TITLE
rename glue view and add sparksql view

### PR DESCRIPTION
**Pull request by Ramshackle-Jamathon**
This pr:
- renames `GlueView` to `GlueAthenaView`, which more accurately reflects what it does
- adds a `GlueSparkSQLView` to support defining views that can be used by spark applications running in EMR or any other spark environment using glue as the metastore.

cc @mapbox/data-tools

### CODE REVIEW

**Comment by rclark** [comment]
I would strongly encourage (a) each of these individually and (b) a "wrapper" shortcut that builds one of each. Naming maybe is the only confusing part.

**Comment by Ramshackle-Jamathon** [comment]
> (b) a "wrapper" shortcut that builds one of each

Keeping in mind that the syntax of sparkSQL and prestoSQL are not cross compatible, what params do you think the combined wrapper would have? Or should it just be implied that you use syntax shared by both when using it?

**Comment by rclark** [comment]
Oh I see what you mean. Ok, let's keep them separated.

Would `GlueSparkView` and `GluePrestoView` be acceptable names?

**Comment by Ramshackle-Jamathon** [comment]
> Would GlueSparkView and GluePrestoView be acceptable names?

👍 yeah that works for me

**Comment by rclark** [comment]
Uh oh. No tests!

Screen Shot 2020-06-15 at 10 57 14 AM

**Pull request merged**
