### PR TITLE
Dereferencing templates

### LINKED ISSUE #13: cf.dereference()
A method that would take:
- env: object defining values for psuedo parameters like `AWS::StackName`
- parameters: object defining values for parameters
- template: a template

Would return the template with all psuedo parameters and intrinsic functions dereferenced.

cc @ianshward @k-mahoney

### PR DESCRIPTION
**Pull request by rclark**
Adds functionality to resolve conditions, intrinsic functions, and pseudo parameters into flat strings.

**TODO**

- [ ] improve test coverage
- [ ] come up with some kind of plan for converting ref/att values into code (https://github.com/mapbox/cloudfriend/issues/13#issuecomment-280927115)
- [ ] implement a dereferencing function as part of cloudfriend's index.js

@k-mahoney on that 3rd point, what would the ideal API for this be from your perspective? To dereference a template you'll need to provide 

- a template
- a set of parameter values
- a set of "deployment options" (stack name, region, account id)

Should it be something like 

```
var cf = require('cloudfriend');
var dereferenced = cf.dereference(template, parameters, options);
```

... or is there some other way to format it that might be more useful for what you need?

Fixes #13

### CODE REVIEW

**Comment by rclark** [comment]
@k-mahoney this is ready for you to take it for a spin! As indicated above, 

```js
var cf = require('cloudfriend');
var dereferenced = cf.dereference(template, parameters, options);
```

**Comment by k-mahoney** [comment]
Awesome, will get this integrated with our tests this week and give it a try!

**Comment by zmully** [comment]
@rclark is improved test coverage something you'd still like to see before this can be merged?

**Comment by k-mahoney** [comment]
As it stands this functionality will only work with **IAM** ref/att values - but I imagine we can get this expanded in a subsequent PR? Scripting that has been on my backlog for a while.

**Comment by rclark** [comment]
This is more scope creep than I thought it would be when I first set down this road. Its a huge pain in the ass to write all the information needed dereferencing into the codebase, and in the long run this would be a maintenance nightmare -- it needs to stay in sync with CloudFormation. There are also a bunch of unsolvable edge cases.

Can we circle back and huddle on your use-case to see if we can come up with a better solution?

**Comment by k-mahoney** [comment]
It might make sense, given that we're only using it for tests at this juncture, to retain the parse/dereference logic and provide a template of the desired ref/att values - rather than maintaining the monolith of all possible values.

**Comment by rclark** [comment]
Closing. This experiment didn't end up being as effective as we'd hoped.

**Pull request closed without merging**
